#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaChallengesTab

#include "Basic.hpp"

#include "AthenaChallengesTab_classes.hpp"
#include "AthenaChallengesTab_parameters.hpp"


namespace SDK
{

// Function AthenaChallengesTab.AthenaChallengesTab_C.ExecuteUbergraph_AthenaChallengesTab
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaChallengesTab_C::ExecuteUbergraph_AthenaChallengesTab(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengesTab_C", "ExecuteUbergraph_AthenaChallengesTab");

	Params::AthenaChallengesTab_C_ExecuteUbergraph_AthenaChallengesTab Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaChallengesTab.AthenaChallengesTab_C.BndEvt__CompendiumBundleTabList_K2Node_ComponentBoundEvent_56_OnTabButtonCreated__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class FName                             TabId                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UCommonButton*                    TabButton                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaChallengesTab_C::BndEvt__CompendiumBundleTabList_K2Node_ComponentBoundEvent_56_OnTabButtonCreated__DelegateSignature(class FName TabId, class UCommonButton* TabButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengesTab_C", "BndEvt__CompendiumBundleTabList_K2Node_ComponentBoundEvent_56_OnTabButtonCreated__DelegateSignature");

	Params::AthenaChallengesTab_C_BndEvt__CompendiumBundleTabList_K2Node_ComponentBoundEvent_56_OnTabButtonCreated__DelegateSignature Parms{};

	Parms.TabId = TabId;
	Parms.TabButton = TabButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaChallengesTab.AthenaChallengesTab_C.BndEvt__CompendiumBundleTabList_K2Node_ComponentBoundEvent_45_OnTabSelected__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class FName                             TabId                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaChallengesTab_C::BndEvt__CompendiumBundleTabList_K2Node_ComponentBoundEvent_45_OnTabSelected__DelegateSignature(class FName TabId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengesTab_C", "BndEvt__CompendiumBundleTabList_K2Node_ComponentBoundEvent_45_OnTabSelected__DelegateSignature");

	Params::AthenaChallengesTab_C_BndEvt__CompendiumBundleTabList_K2Node_ComponentBoundEvent_45_OnTabSelected__DelegateSignature Parms{};

	Parms.TabId = TabId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaChallengesTab.AthenaChallengesTab_C.OnDeactivated
// (Event, Protected, BlueprintEvent)

void UAthenaChallengesTab_C::OnDeactivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengesTab_C", "OnDeactivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaChallengesTab.AthenaChallengesTab_C.OnActivated
// (Event, Protected, BlueprintEvent)

void UAthenaChallengesTab_C::OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengesTab_C", "OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaChallengesTab.AthenaChallengesTab_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UAthenaChallengesTab_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengesTab_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaChallengesTab.AthenaChallengesTab_C.RegisterEventListeners
// (Public, BlueprintCallable, BlueprintEvent)

void UAthenaChallengesTab_C::RegisterEventListeners()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengesTab_C", "RegisterEventListeners");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaChallengesTab.AthenaChallengesTab_C.HandleChallengesChanged
// (Public, BlueprintCallable, BlueprintEvent)

void UAthenaChallengesTab_C::HandleChallengesChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengesTab_C", "HandleChallengesChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaChallengesTab.AthenaChallengesTab_C.UpdateChallengeViews
// (Public, BlueprintCallable, BlueprintEvent)

void UAthenaChallengesTab_C::UpdateChallengeViews()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengesTab_C", "UpdateChallengeViews");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaChallengesTab.AthenaChallengesTab_C.CreateTab
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFortChallengeBundleScheduleDefinition*ScheduleDefinition                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ContentWidget                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaChallengesTab_C::CreateTab(class UFortChallengeBundleScheduleDefinition* ScheduleDefinition, class UWidget* ContentWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengesTab_C", "CreateTab");

	Params::AthenaChallengesTab_C_CreateTab Parms{};

	Parms.ScheduleDefinition = ScheduleDefinition;
	Parms.ContentWidget = ContentWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaChallengesTab.AthenaChallengesTab_C.ResetTabs
// (Public, BlueprintCallable, BlueprintEvent)

void UAthenaChallengesTab_C::ResetTabs()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengesTab_C", "ResetTabs");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaChallengesTab.AthenaChallengesTab_C.HandleTabSelected
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             TabId                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaChallengesTab_C::HandleTabSelected(class FName TabId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengesTab_C", "HandleTabSelected");

	Params::AthenaChallengesTab_C_HandleTabSelected Parms{};

	Parms.TabId = TabId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaChallengesTab.AthenaChallengesTab_C.HandleTabButtonCreated
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             TabId                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UCommonButton*                    Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaChallengesTab_C::HandleTabButtonCreated(class FName TabId, class UCommonButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengesTab_C", "HandleTabButtonCreated");

	Params::AthenaChallengesTab_C_HandleTabButtonCreated Parms{};

	Parms.TabId = TabId;
	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaChallengesTab.AthenaChallengesTab_C.SetupViewedItemData
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFortItem*                        Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaChallengesTab_C::SetupViewedItemData(class UFortItem* Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengesTab_C", "SetupViewedItemData");

	Params::AthenaChallengesTab_C_SetupViewedItemData Parms{};

	Parms.Item = Item;

	UObject::ProcessEvent(Func, &Parms);
}

}

