#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_CameraRainDrops_01

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_CameraRainDrops_01.B_CameraRainDrops_01_C
// 0x0010 (0x03E0 - 0x03D0)
class AB_CameraRainDrops_01_C final : public AEmitterCameraLensEffectBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03D0(0x0008)(Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_B_CameraRainDrops_01(int32 EntryPoint);
	void ReceiveBeginPlay();
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_CameraRainDrops_01_C">();
	}
	static class AB_CameraRainDrops_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_CameraRainDrops_01_C>();
	}
};
static_assert(alignof(AB_CameraRainDrops_01_C) == 0x000010, "Wrong alignment on AB_CameraRainDrops_01_C");
static_assert(sizeof(AB_CameraRainDrops_01_C) == 0x0003E0, "Wrong size on AB_CameraRainDrops_01_C");
static_assert(offsetof(AB_CameraRainDrops_01_C, UberGraphFrame) == 0x0003D0, "Member 'AB_CameraRainDrops_01_C::UberGraphFrame' has a wrong offset!");

}

