#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyle_OutlineLarge_Red

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-OutlineLarge-Red.ButtonStyle-OutlineLarge-Red_C
// 0x0000 (0x0470 - 0x0470)
class UButtonStyle_OutlineLarge_Red_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-OutlineLarge-Red_C">();
	}
	static class UButtonStyle_OutlineLarge_Red_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyle_OutlineLarge_Red_C>();
	}
};
static_assert(alignof(UButtonStyle_OutlineLarge_Red_C) == 0x000008, "Wrong alignment on UButtonStyle_OutlineLarge_Red_C");
static_assert(sizeof(UButtonStyle_OutlineLarge_Red_C) == 0x000470, "Wrong size on UButtonStyle_OutlineLarge_Red_C");

}

