#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyle_Primary_M

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Primary-M.ButtonStyle-Primary-M_C
// 0x0000 (0x0470 - 0x0470)
class UButtonStyle_Primary_M_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-Primary-M_C">();
	}
	static class UButtonStyle_Primary_M_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyle_Primary_M_C>();
	}
};
static_assert(alignof(UButtonStyle_Primary_M_C) == 0x000008, "Wrong alignment on UButtonStyle_Primary_M_C");
static_assert(sizeof(UButtonStyle_Primary_M_C) == 0x000470, "Wrong size on UButtonStyle_Primary_M_C");

}

