#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyle_LeftBox

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-LeftBox.ButtonStyle-LeftBox_C
// 0x0000 (0x0470 - 0x0470)
class UButtonStyle_LeftBox_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-LeftBox_C">();
	}
	static class UButtonStyle_LeftBox_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyle_LeftBox_C>();
	}
};
static_assert(alignof(UButtonStyle_LeftBox_C) == 0x000008, "Wrong alignment on UButtonStyle_LeftBox_C");
static_assert(sizeof(UButtonStyle_LeftBox_C) == 0x000470, "Wrong size on UButtonStyle_LeftBox_C");

}

