#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GAB_SurvivorDBNORevive

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GAB_SurvivorDBNORevive.GAB_SurvivorDBNORevive_C
// 0x0008 (0x0AB8 - 0x0AB0)
class UGAB_SurvivorDBNORevive_C final : public UFortGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0AB0(0x0008)(Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GAB_SurvivorDBNORevive(int32 EntryPoint);
	void K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData);
	void K2_OnEndAbility(bool bWasCancelled);
	void OnBlendOut_2491B74745BECED77F7B838860EC4602();
	void OnCancelled_2491B74745BECED77F7B838860EC4602();
	void OnCompleted_2491B74745BECED77F7B838860EC4602();
	void OnInterrupted_2491B74745BECED77F7B838860EC4602();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GAB_SurvivorDBNORevive_C">();
	}
	static class UGAB_SurvivorDBNORevive_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGAB_SurvivorDBNORevive_C>();
	}
};
static_assert(alignof(UGAB_SurvivorDBNORevive_C) == 0x000008, "Wrong alignment on UGAB_SurvivorDBNORevive_C");
static_assert(sizeof(UGAB_SurvivorDBNORevive_C) == 0x000AB8, "Wrong size on UGAB_SurvivorDBNORevive_C");
static_assert(offsetof(UGAB_SurvivorDBNORevive_C, UberGraphFrame) == 0x000AB0, "Member 'UGAB_SurvivorDBNORevive_C::UberGraphFrame' has a wrong offset!");

}

