#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LoginScreen

#include "Basic.hpp"

#include "LoginScreen_classes.hpp"
#include "LoginScreen_parameters.hpp"


namespace SDK
{

// Function LoginScreen.LoginScreen_C.ExecuteUbergraph_LoginScreen
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULoginScreen_C::ExecuteUbergraph_LoginScreen(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "ExecuteUbergraph_LoginScreen");

	Params::LoginScreen_C_ExecuteUbergraph_LoginScreen Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoginScreen.LoginScreen_C.OnEulaDownloadComplete
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bSuccessful                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const class FText&                      EULAText                                               (BlueprintVisible, BlueprintReadOnly, Parm)

void ULoginScreen_C::OnEulaDownloadComplete(bool bSuccessful, const class FText& EULAText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "OnEulaDownloadComplete");

	Params::LoginScreen_C_OnEulaDownloadComplete Parms{};

	Parms.bSuccessful = bSuccessful;
	Parms.EULAText = std::move(EULAText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoginScreen.LoginScreen_C.OnExitState
// (Event, Public, BlueprintEvent)
// Parameters:
// EFortUIState                            NextUIState                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULoginScreen_C::OnExitState(EFortUIState NextUIState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "OnExitState");

	Params::LoginScreen_C_OnExitState Parms{};

	Parms.NextUIState = NextUIState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoginScreen.LoginScreen_C.HandleLoginResultConfirmed
// (Event, Protected, BlueprintEvent)

void ULoginScreen_C::HandleLoginResultConfirmed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "HandleLoginResultConfirmed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginScreen.LoginScreen_C.RollbackStackToSplashScreen
// (Event, Protected, BlueprintEvent)

void ULoginScreen_C::RollbackStackToSplashScreen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "RollbackStackToSplashScreen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginScreen.LoginScreen_C.SafePopFlowStack
// (Event, Protected, BlueprintEvent)

void ULoginScreen_C::SafePopFlowStack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "SafePopFlowStack");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginScreen.LoginScreen_C.EmptyFlowStack
// (Event, Protected, BlueprintEvent)

void ULoginScreen_C::EmptyFlowStack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "EmptyFlowStack");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginScreen.LoginScreen_C.ActivateWidgetOnFlowStack
// (Event, Protected, BlueprintEvent)

void ULoginScreen_C::ActivateWidgetOnFlowStack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "ActivateWidgetOnFlowStack");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginScreen.LoginScreen_C.PushWidgetOntoFlowStack
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UWidget*                          Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULoginScreen_C::PushWidgetOntoFlowStack(class UWidget* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "PushWidgetOntoFlowStack");

	Params::LoginScreen_C_PushWidgetOntoFlowStack Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoginScreen.LoginScreen_C.OnWebLoginClosed
// (BlueprintCallable, BlueprintEvent)

void ULoginScreen_C::OnWebLoginClosed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "OnWebLoginClosed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginScreen.LoginScreen_C.OnWebLoginDisplay
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          WebWidget                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULoginScreen_C::OnWebLoginDisplay(class UWidget* WebWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "OnWebLoginDisplay");

	Params::LoginScreen_C_OnWebLoginDisplay Parms{};

	Parms.WebWidget = WebWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoginScreen.LoginScreen_C.Event Closed MOTD
// (BlueprintCallable, BlueprintEvent)

void ULoginScreen_C::Event_Closed_MOTD()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "Event Closed MOTD");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginScreen.LoginScreen_C.OnShowLoginMessage
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// bool                                    bShow                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const class FText&                      Tile                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const class FText&                      Body                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ULoginScreen_C::OnShowLoginMessage(bool bShow, const class FText& Tile, const class FText& Body)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "OnShowLoginMessage");

	Params::LoginScreen_C_OnShowLoginMessage Parms{};

	Parms.bShow = bShow;
	Parms.Tile = std::move(Tile);
	Parms.Body = std::move(Body);

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoginScreen.LoginScreen_C.OnPostLoginLogoutComplete
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      Reason                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ULoginScreen_C::OnPostLoginLogoutComplete(const class FText& Reason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "OnPostLoginLogoutComplete");

	Params::LoginScreen_C_OnPostLoginLogoutComplete Parms{};

	Parms.Reason = std::move(Reason);

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoginScreen.LoginScreen_C.OnNeedsPurchaseOrAccountLinking
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bLinkedAccountNeedsPurchase                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ULoginScreen_C::OnNeedsPurchaseOrAccountLinking(bool bLinkedAccountNeedsPurchase)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "OnNeedsPurchaseOrAccountLinking");

	Params::LoginScreen_C_OnNeedsPurchaseOrAccountLinking Parms{};

	Parms.bLinkedAccountNeedsPurchase = bLinkedAccountNeedsPurchase;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoginScreen.LoginScreen_C.AccountLinking_ViewEula
// (BlueprintCallable, BlueprintEvent)

void ULoginScreen_C::AccountLinking_ViewEula()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "AccountLinking_ViewEula");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginScreen.LoginScreen_C.BndEvt__IconTextButton_K2Node_ComponentBoundEvent_20_CommonButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButton*                    Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULoginScreen_C::BndEvt__IconTextButton_K2Node_ComponentBoundEvent_20_CommonButtonClicked__DelegateSignature(class UCommonButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "BndEvt__IconTextButton_K2Node_ComponentBoundEvent_20_CommonButtonClicked__DelegateSignature");

	Params::LoginScreen_C_BndEvt__IconTextButton_K2Node_ComponentBoundEvent_20_CommonButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoginScreen.LoginScreen_C.PushContentWidgetInternal
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UWidget*                          Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FContentPushState&         State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void ULoginScreen_C::PushContentWidgetInternal(class UWidget* Widget, const struct FContentPushState& State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "PushContentWidgetInternal");

	Params::LoginScreen_C_PushContentWidgetInternal Parms{};

	Parms.Widget = Widget;
	Parms.State = std::move(State);

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoginScreen.LoginScreen_C.AccountLinking_RequestAutoLogin
// (BlueprintCallable, BlueprintEvent)

void ULoginScreen_C::AccountLinking_RequestAutoLogin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "AccountLinking_RequestAutoLogin");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginScreen.LoginScreen_C.AccountLinking_RequestSignIn
// (BlueprintCallable, BlueprintEvent)

void ULoginScreen_C::AccountLinking_RequestSignIn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "AccountLinking_RequestSignIn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginScreen.LoginScreen_C.AccountLinking_LinkingFailed
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      FailReason                                             (BlueprintVisible, BlueprintReadOnly, Parm)

void ULoginScreen_C::AccountLinking_LinkingFailed(const class FText& FailReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "AccountLinking_LinkingFailed");

	Params::LoginScreen_C_AccountLinking_LinkingFailed Parms{};

	Parms.FailReason = std::move(FailReason);

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoginScreen.LoginScreen_C.AccountLinking_PopStatus
// (BlueprintCallable, BlueprintEvent)

void ULoginScreen_C::AccountLinking_PopStatus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "AccountLinking_PopStatus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginScreen.LoginScreen_C.AccountLinking_PushStatus
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      StatusText                                             (BlueprintVisible, BlueprintReadOnly, Parm)

void ULoginScreen_C::AccountLinking_PushStatus(const class FText& StatusText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "AccountLinking_PushStatus");

	Params::LoginScreen_C_AccountLinking_PushStatus Parms{};

	Parms.StatusText = std::move(StatusText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoginScreen.LoginScreen_C.OnLoginSuceeded
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ULoginScreen_C::OnLoginSuceeded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "OnLoginSuceeded");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginScreen.LoginScreen_C.OnEnterState
// (Event, Public, BlueprintEvent)
// Parameters:
// EFortUIState                            PreviousUIState                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULoginScreen_C::OnEnterState(EFortUIState PreviousUIState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "OnEnterState");

	Params::LoginScreen_C_OnEnterState Parms{};

	Parms.PreviousUIState = PreviousUIState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoginScreen.LoginScreen_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void ULoginScreen_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginScreen.LoginScreen_C.ShowAccountLinkingWindow
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    InLinkedAccountNeedsPurchase                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ULoginScreen_C::ShowAccountLinkingWindow(bool InLinkedAccountNeedsPurchase)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "ShowAccountLinkingWindow");

	Params::LoginScreen_C_ShowAccountLinkingWindow Parms{};

	Parms.InLinkedAccountNeedsPurchase = InLinkedAccountNeedsPurchase;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoginScreen.LoginScreen_C.ToggleLoginMenu
// (Public, BlueprintCallable, BlueprintEvent)

void ULoginScreen_C::ToggleLoginMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "ToggleLoginMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginScreen.LoginScreen_C.OnMouseButtonUp_MenuBorder
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FPointerEvent&                   MouseEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply ULoginScreen_C::OnMouseButtonUp_MenuBorder(const struct FGeometry& MyGeometry, struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "OnMouseButtonUp_MenuBorder");

	Params::LoginScreen_C_OnMouseButtonUp_MenuBorder Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	MouseEvent = std::move(Parms.MouseEvent);

	return Parms.ReturnValue;
}


// Function LoginScreen.LoginScreen_C.GetLoginMenu
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* ULoginScreen_C::GetLoginMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "GetLoginMenu");

	Params::LoginScreen_C_GetLoginMenu Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function LoginScreen.LoginScreen_C.PopContentWidgetInternal
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FContentPushState&         State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* ULoginScreen_C::PopContentWidgetInternal(const struct FContentPushState& State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "PopContentWidgetInternal");

	Params::LoginScreen_C_PopContentWidgetInternal Parms{};

	Parms.State = std::move(State);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function LoginScreen.LoginScreen_C.RollbackToSplashScreen
// (Public, BlueprintCallable, BlueprintEvent)

void ULoginScreen_C::RollbackToSplashScreen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "RollbackToSplashScreen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginScreen.LoginScreen_C.HideNonSplashScreenContent
// (Public, BlueprintCallable, BlueprintEvent)

void ULoginScreen_C::HideNonSplashScreenContent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "HideNonSplashScreenContent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginScreen.LoginScreen_C.EmptyLoginStack
// (Public, BlueprintCallable, BlueprintEvent)

void ULoginScreen_C::EmptyLoginStack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "EmptyLoginStack");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginScreen.LoginScreen_C.SafePopContent
// (Public, BlueprintCallable, BlueprintEvent)

void ULoginScreen_C::SafePopContent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "SafePopContent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginScreen.LoginScreen_C.CloseWebLogin
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   bWasClosed                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ULoginScreen_C::CloseWebLogin(bool* bWasClosed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "CloseWebLogin");

	Params::LoginScreen_C_CloseWebLogin Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bWasClosed != nullptr)
		*bWasClosed = Parms.bWasClosed;
}


// Function LoginScreen.LoginScreen_C.DismissWebLogin
// (Public, BlueprintCallable, BlueprintEvent)

void ULoginScreen_C::DismissWebLogin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "DismissWebLogin");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginScreen.LoginScreen_C.ShowExternalLogin
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          NativeWidget                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULoginScreen_C::ShowExternalLogin(class UWidget* NativeWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoginScreen_C", "ShowExternalLogin");

	Params::LoginScreen_C_ShowExternalLogin Parms{};

	Parms.NativeWidget = NativeWidget;

	UObject::ProcessEvent(Func, &Parms);
}

}

