#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerPawn_Generic

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "PlayerPawn_Generic_Parent_classes.hpp"
#include "FortniteGame_structs.hpp"
#include "PlayerWindParticleEmitters_structs.hpp"
#include "GameplayAbilities_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass PlayerPawn_Generic.PlayerPawn_Generic_C
// 0x0530 (0x1CF0 - 0x17C0)
#pragma pack(push, 0x1)
class alignas(0x10) APlayerPawn_Generic_C : public APlayerPawn_Generic_Parent_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_PlayerPawn_Generic_C;               // 0x17C0(0x0008)(Transient, DuplicateTransient)
	class UParticleSystemComponent*               SplashEffectsForEnteringOrExitingWater;            // 0x17C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               GamplayWindInteractionEffects;                     // 0x17D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               Effect_Player_Run_Land;                            // 0x17D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               Effect_Player_Walk_Land;                           // 0x17E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               Effect_Player_Walk_Water;                          // 0x17E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               Effect_Player_Run_Water;                           // 0x17F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               Effect_WaterInteraction_FX;                        // 0x17F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               AnimTrailPS;                                       // 0x1800(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               HitDamageParticles;                                // 0x1808(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UWidgetComponent*                       SpeechBubbleComponent;                             // 0x1810(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    PlayerLight;                                       // 0x1818(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         CapsuleFadeTL_RemoveShadow_018B40864B973FCD649A23BAC2709F23; // 0x1820(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            CapsuleFadeTL__Direction_018B40864B973FCD649A23BAC2709F23; // 0x1824(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1825[0x3];                                     // 0x1825(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     CapsuleFadeTL;                                     // 0x1828(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Full_Shield_Health_Push_6222ABB047B8F22E3C9FC983BD70CEA6; // 0x1830(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Full_Shield_Health_Impact_6222ABB047B8F22E3C9FC983BD70CEA6; // 0x1834(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Full_Shield_Health__Direction_6222ABB047B8F22E3C9FC983BD70CEA6; // 0x1838(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1839[0x7];                                     // 0x1839(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Full_Shield_Health;                                // 0x1840(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Shield_DamageTimeline_Impact_6DC09F024CD096186AE1389FB8061E30; // 0x1848(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Shield_DamageTimeline__Direction_6DC09F024CD096186AE1389FB8061E30; // 0x184C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_184D[0x3];                                     // 0x184D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Shield_DamageTimeline;                             // 0x1850(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Shield_Regen_Timeline_Opacity_3DC9958C47D4CEFA60E68699D92BA374; // 0x1858(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Shield_Regen_Timeline_Push_3DC9958C47D4CEFA60E68699D92BA374; // 0x185C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Shield_Regen_Timeline__Direction_3DC9958C47D4CEFA60E68699D92BA374; // 0x1860(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1861[0x7];                                     // 0x1861(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Shield_Regen_Timeline;                             // 0x1868(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Shield_ShatterTimeline_Push_F3223F2D4A6B8642F950B0A15F8C6699; // 0x1870(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Shield_ShatterTimeline_Opacity_F3223F2D4A6B8642F950B0A15F8C6699; // 0x1874(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Shield_ShatterTimeline_HighlightCracks_F3223F2D4A6B8642F950B0A15F8C6699; // 0x1878(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Shield_ShatterTimeline__Direction_F3223F2D4A6B8642F950B0A15F8C6699; // 0x187C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_187D[0x3];                                     // 0x187D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Shield_ShatterTimeline;                            // 0x1880(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         HealthSweep_SafetyOpacity_2A96303441845D0EAAAB1EB68183F8A8; // 0x1888(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         HealthSweep_Sweep_2A96303441845D0EAAAB1EB68183F8A8; // 0x188C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            HealthSweep__Direction_2A96303441845D0EAAAB1EB68183F8A8; // 0x1890(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1891[0x7];                                     // 0x1891(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     HealthSweep;                                       // 0x1898(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 ScreenEffect_PlayerHealthDamageDirection;          // 0x18A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 ScreenEffect_PlayerHealthDamage;                   // 0x18A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 ScreenEffect_PlayerShieldDamageDirection;          // 0x18B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 ScreenEffect_PlayerShieldDamage;                   // 0x18B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 HitByHuskProjectileClass;                          // 0x18C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             HitByHuskRangedSound;                              // 0x18C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             HitByHuskMeleeSound;                               // 0x18D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           SoulSuckVictimMontage;                             // 0x18D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         PlayerSpeed;                                       // 0x18E0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Run_Particle_Activate_Speed;                       // 0x18E4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Walk_Dust_Activate_Speed;                          // 0x18E8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Walk_Particle_Reset_Speed;                         // 0x18EC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                PreviousVelocityVector;                            // 0x18F0(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CanSpawnRunKickupFX_;                              // 0x18FC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          CanSpawnWalkKickupFX_;                             // 0x18FD(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          CanSpawnDustLandFX_;                               // 0x18FE(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          IsInWater;                                         // 0x18FF(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FRotator                               RunWalkParticleRotation;                           // 0x1900(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          IsNinjaInShadowStance_;                            // 0x190C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_190D[0x3];                                     // 0x190D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  GameplayTagsForHitByHuskMeleeSound;                // 0x1910(0x0020)(Edit, BlueprintVisible)
	class UMaterialInterface*                     Adrenaline_Material;                               // 0x1930(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UMaterialInstanceDynamic*>       AdrenalineRush_HeadAnimatingMIDS;                  // 0x1938(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	TArray<class UMaterialInstanceDynamic*>       AdrenalineRush_BodyAnimatingMIDS;                  // 0x1948(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	struct FLinearColor                           Adrenaline_Rush_Color_Outer_Direct;                // 0x1958(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Adrenaline_Rush_Color_Inner_Direct;                // 0x1968(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Adrenaline_Rush_WPO_Offset;                        // 0x1978(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_197C[0x4];                                     // 0x197C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystemComponent*               P_AdrenalineRushSparklesRunning;                   // 0x1980(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     Shield_Material;                                   // 0x1988(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UMaterialInstanceDynamic*>       BodyShieldMIDArray;                                // 0x1990(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	TArray<class UMaterialInstanceDynamic*>       HeadShieldMIDArray;                                // 0x19A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	bool                                          Shield_Active;                                     // 0x19B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19B1[0x3];                                     // 0x19B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         WaterCounter;                                      // 0x19B4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Tick_Delta_Seconds;                                // 0x19B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Shield_Damage_Wave_Animation;                      // 0x19BC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Overall_Shield_Damage_Wave_Animation_Length;       // 0x19C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         size;                                              // 0x19C4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Dying;                                             // 0x19C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          CanRippleAgain;                                    // 0x19C9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19CA[0x6];                                     // 0x19CA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundBase*                             Sound_Shield_Impact;                               // 0x19D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Sound_Shield_Destroyed;                            // 0x19D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Sound_Shield_FullyCharged;                         // 0x19E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Sound_Shield_StartRecharge;                        // 0x19E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Shield_Shatter_Opacity;                            // 0x19F0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Regen_Opacity;                                     // 0x19F4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Damage_Opacity;                                    // 0x19F8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Default_Shield_opacity;                            // 0x19FC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Shield_PushMinValue;                               // 0x1A00(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ShieldVisible_Hit;                                 // 0x1A04(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          ShieldVisible_Recover;                             // 0x1A05(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          ShieldVisible_Shatter;                             // 0x1A06(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          ShieldVisible_FullHealth;                          // 0x1A07(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	float                                         Fully_Regened_Shield_health_Opacity;               // 0x1A08(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1A0C[0x4];                                     // 0x1A0C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  TC_GameplayCueDamageShielded;                      // 0x1A10(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          LatestDamageIsShieldDamage;                        // 0x1A30(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1A31[0x3];                                     // 0x1A31(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Damage_Taken;                                      // 0x1A34(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Last_Shield_Damage_Time;                           // 0x1A38(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1A3C[0x4];                                     // 0x1A3C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UMaterialInstanceDynamic*>       CharmShieldMIDArray;                               // 0x1A40(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	bool                                          BodyValid;                                         // 0x1A50(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          BackpackValid;                                     // 0x1A51(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          HatValid;                                          // 0x1A52(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          FaceValid;                                         // 0x1A53(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          CharmValid;                                        // 0x1A54(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          HeadValid;                                         // 0x1A55(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1A56[0x2];                                     // 0x1A56(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UMaterialInstanceDynamic*>       AdrenalineRush_CharmAnimatingMIDS;                 // 0x1A58(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	TArray<class UMaterialInstanceDynamic*>       Adrenaline_Rush_MID_Collection;                    // 0x1A68(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	class UParticleSystem*                        P_DBNOResurrect;                                   // 0x1A78(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             DBNOResurrectSound;                                // 0x1A80(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          On_Player_Built_Floor;                             // 0x1A88(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor)
	uint8                                         Pad_1A89[0x7];                                     // 0x1A89(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           Event_NeedRoadsActive;                             // 0x1A90(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           Event_NeedRoadsDeactive;                           // 0x1A98(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer                  TC_WhereWereGoingWeNeedRoads;                      // 0x1AA0(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UParticleSystem*                        Effect_Player_LandedDust;                          // 0x1AC0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               P_GravitySphere_LeftFoot;                          // 0x1AC8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UMaterialInstanceDynamic*>       TempArray;                                         // 0x1AD0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	class UParticleSystemComponent*               P_GravitySphere_RightFoot;                         // 0x1AE0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        Effect_Player_GravitySphereFeet;                   // 0x1AE8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Shield_BodySkeletalMesh;                           // 0x1AF0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Shield_HeadSkeletalMesh;                           // 0x1AF8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Shield_CharmSkeletalMesh;                          // 0x1B00(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Adrenaline_Rush_Body;                              // 0x1B08(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Adrenaline_Rush_Head;                              // 0x1B10(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Adrenaline_Rush_Charm;                             // 0x1B18(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Sound_Player_Hit;                                  // 0x1B20(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UForceFeedbackEffect*                   DamageForceFeedback;                               // 0x1B28(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               DBNOParticles;                                     // 0x1B30(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        Effect_Player_Landed_WindVector_P;                 // 0x1B38(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 SpeechBubbleWidgetClass;                           // 0x1B40(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   LastSpeechText;                                    // 0x1B48(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UClass*                                 DamageCameraShake;                                 // 0x1B60(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          UseAnimTrailsNotifies;                             // 0x1B68(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1B69[0x3];                                     // 0x1B69(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Time_when_you_ll_be_able_to_splash_again;          // 0x1B6C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class A_WaterMeshBlueprintMaster_C*           CurrentWaterMeshActor;                             // 0x1B70(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             WaterTraceHitLocation;                             // 0x1B78(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FVector                                StableVelocityVector;                              // 0x1C00(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C0C[0x4];                                     // 0x1C0C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystem*                        PlayerRunTemplate_Ground;                          // 0x1C10(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        PlayerWalkTemplate_Ground;                         // 0x1C18(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        PlayerRunTemplate_Water;                           // 0x1C20(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        PlayerWalkTemplate_Water;                          // 0x1C28(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMesh*                          Pawn_Charm_Skeletal_Mesh;                          // 0x1C30(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DefaultShieldOpacity;                              // 0x1C38(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C3C[0x4];                                     // 0x1C3C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystemComponent*               AnimTrailsPS_Ref;                                  // 0x1C40(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Adrenaline_Rush_Color_Outer_Periodic;              // 0x1C48(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     WeaponMaterialOverride;                            // 0x1C58(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Adrenaline_Rush_Color_Inner_Periodic;              // 0x1C60(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          TickWaterLevel;                                    // 0x1C70(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1C71[0x7];                                     // 0x1C71(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTextureRenderTarget2D*                 WetnessDepthTexture;                               // 0x1C78(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               WaterLevelMID;                                     // 0x1C80(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               WaterDecayMID;                                     // 0x1C88(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Was_RTT_Enabled_Var_Set;                           // 0x1C90(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Water_Scene_Capture_Enabled;                       // 0x1C91(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1C92[0x2];                                     // 0x1C92(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         StartingMinCapsuleShadowVis;                       // 0x1C94(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CachedEffect;                                      // 0x1C98(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UMaterialInstanceDynamic*>       WaterInteractionWakeMIDS;                          // 0x1CA0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	TArray<class UStaticMeshComponent*>           WaterInteractionWakeMeshes;                        // 0x1CB0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	float                                         Character_Calve_Length;                            // 0x1CC0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         NumberOfCyclingWaterMeshes;                        // 0x1CC4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           WaterTraceImpactNormalAndZHeightLocation;          // 0x1CC8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                PlayerVelocity;                                    // 0x1CD8(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_PlayerPawn_Generic(int32 EntryPoint);
	void AnimTrailsNotify(bool bActive);
	void AnimTrailsDisable();
	void AnimTrailsSetup(class UParticleSystem* ParticleSystemReference, class FName FirstSocketName, class FName SecondSocketName, float Width);
	void GameplayCue_Shield_Reapplied(EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters);
	void GameplayCue_Shield_FullyCharged(EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters);
	void GameplayCue_Shield_Destroyed(EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters);
	void GameplayCue_Damage_Shielded(EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters);
	void GameplayCue_Generic_AdrenalineRush_DirectHeal(EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters);
	void Test_Adrenaline_Rush();
	void OnLand_CE();
	void Player_Creates_a_Splash(const struct FTransform& NewTransform);
	void PlayGameplayWindEffect(EPlayerWindParticleEmitters Player_Wind_Particle_Emitter_To_Fire);
	void SpawnDBNOParticles(const struct FVector& ParticleLocation, const struct FVector& HitNormal);
	void FadeOutCapsuleShadow();
	void BindOnDestroyed();
	void CharacterDestroyed(class AActor* DestroyedActor);
	void Entered_WaterVolume();
	void OnDeathServer(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AController* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext);
	void Clean_up_DBNO_fx();
	void MultiEndSwap(class AFortWeapon* CurrentWeapon_0);
	void UnBindWeaponSwap();
	void MultiSwapWeapon(class AFortWeapon* New, class AFortWeapon* Prev);
	void BindWeaponSwap(float InDuration);
	void ClientBindWeaponSwap(class AFortWeapon* NewWeapon, class AFortWeapon* PrevWeapon);
	void ReceiveDestroyed();
	void CleanupGravitySphereFootEffects();
	void OnClearSentence();
	void OnDisplaySentence(const class FText& SpeechText);
	void ReceivePossessed(class AController* NewController);
	void OnBaseChanged(class AActor* NewBase);
	void GameplayCue_Abilities_Activation_DBNOResurrect(EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters);
	void InternalSetFirstPersonCamera(bool NewUseFirstPersonCamera);
	void GameplayCue_GravitySphere(EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters);
	void SetFirstPersonCamera(bool bNewUseFirstPersonCamera);
	void GameplayCue_Abilities_Activation_Generic_HarvestBuff_Tier2(EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters);
	void GameplayCue_Abilities_Activation_Generic_HarvestBuff_Tier1(EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters);
	void OnCharacterPartsReinitialized();
	void FootStepRight();
	void FootStepLeft();
	void ReceiveTick(float DeltaSeconds);
	void OnWeaponEquipped(class AFortWeapon* NewWeapon, class AFortWeapon* PrevWeapon);
	void OnDeathPlayEffects(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AFortPawn* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext);
	void OnLanded(const struct FHitResult& Hit);
	void OnDamagePlayEffects(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AFortPawn* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext);
	void MeleeSwingLeft();
	void MeleeSwingRight();
	void Full_Shield_Health__UpdateFunc();
	void Full_Shield_Health__FinishedFunc();
	void Shield_DamageTimeline__UpdateFunc();
	void Shield_DamageTimeline__FinishedFunc();
	void Shield_ShatterTimeline__UpdateFunc();
	void Shield_ShatterTimeline__FinishedFunc();
	void Shield_Regen_Timeline__UpdateFunc();
	void Shield_Regen_Timeline__FinishedFunc();
	void HealthSweep__UpdateFunc();
	void HealthSweep__FinishedFunc();
	void CapsuleFadeTL__UpdateFunc();
	void CapsuleFadeTL__FinishedFunc();
	void UserConstructionScript();
	void Create_and_Duplicate_Effect_Skeletal_Meshes_Parent(EFortCustomPartType BodyType, class USkeletalMeshComponent*& DuplicatedSkeletalMeshComponent, class UMaterialInterface* Material_to_Apply, TArray<class UMaterialInstanceDynamic*>& Empty_MID_Array, int32 TranslucentSortPriority);
	void FindShieldOpacity();
	void SetShieldMids(float Highlight_Cracks, bool Set_Highlight_Cracks, float Push, bool Set_Push);
	void SetShieldMids_InternalLoop(float Highlight_Cracks, bool Set_Highlight_Cracks, float Push, bool Set_Push, TArray<class UMaterialInstanceDynamic*>& NewParam1);
	void SlaveAMeshToTheBody(class USkeletalMeshComponent* Mesh_0, class USkeletalMeshComponent* Master);
	void ToggleShieldVisibility();
	void Create_and_Duplicate_Effect_Poseable_Skeletal_Mesh(EFortCustomPartType BodyType, class UMaterialInterface* Material_to_Apply, TArray<class UMaterialInstanceDynamic*>& Empty_MID_Array, int32 TranslucentSortPriority, class UPoseableMeshComponent*& PoseableMesh);
	void Setup_FX_Mesh_Duplicates(class UMaterialInterface*& Material_to_Apply, TArray<class UMaterialInstanceDynamic*>& Charm_MID_Array, class USkeletalMeshComponent*& Charm_Mesh, TArray<class UMaterialInstanceDynamic*>& Head_MID_Array, class USkeletalMeshComponent*& Head_Mesh, TArray<class UMaterialInstanceDynamic*>& Body_MID_Array, class USkeletalMeshComponent*& Body_Mesh, int32 Translucent_Sort_Order, bool Transfer_Material_Parameters);
	void OnRep_On_Player_Built_Floor();
	void SetAdrenalineRushVisibility(bool Visible);
	void DisableWaterLevelTick();
	void Are_the_wind_and_water_RTT_passes_enabled(bool* NewParam);
	void TriggerGameplayWindEmitter(EPlayerWindParticleEmitters Player_Wind_Particle_Emitter_To_Fire);
	void Melee_Effect_Color(struct FVector* Melee_Color_Set);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PlayerPawn_Generic_C">();
	}
	static class APlayerPawn_Generic_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APlayerPawn_Generic_C>();
	}
};
#pragma pack(pop)
static_assert(alignof(APlayerPawn_Generic_C) == 0x000010, "Wrong alignment on APlayerPawn_Generic_C");
static_assert(sizeof(APlayerPawn_Generic_C) == 0x001CF0, "Wrong size on APlayerPawn_Generic_C");
static_assert(offsetof(APlayerPawn_Generic_C, UberGraphFrame_PlayerPawn_Generic_C) == 0x0017C0, "Member 'APlayerPawn_Generic_C::UberGraphFrame_PlayerPawn_Generic_C' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, SplashEffectsForEnteringOrExitingWater) == 0x0017C8, "Member 'APlayerPawn_Generic_C::SplashEffectsForEnteringOrExitingWater' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, GamplayWindInteractionEffects) == 0x0017D0, "Member 'APlayerPawn_Generic_C::GamplayWindInteractionEffects' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Effect_Player_Run_Land) == 0x0017D8, "Member 'APlayerPawn_Generic_C::Effect_Player_Run_Land' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Effect_Player_Walk_Land) == 0x0017E0, "Member 'APlayerPawn_Generic_C::Effect_Player_Walk_Land' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Effect_Player_Walk_Water) == 0x0017E8, "Member 'APlayerPawn_Generic_C::Effect_Player_Walk_Water' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Effect_Player_Run_Water) == 0x0017F0, "Member 'APlayerPawn_Generic_C::Effect_Player_Run_Water' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Effect_WaterInteraction_FX) == 0x0017F8, "Member 'APlayerPawn_Generic_C::Effect_WaterInteraction_FX' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, AnimTrailPS) == 0x001800, "Member 'APlayerPawn_Generic_C::AnimTrailPS' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, HitDamageParticles) == 0x001808, "Member 'APlayerPawn_Generic_C::HitDamageParticles' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, SpeechBubbleComponent) == 0x001810, "Member 'APlayerPawn_Generic_C::SpeechBubbleComponent' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, PlayerLight) == 0x001818, "Member 'APlayerPawn_Generic_C::PlayerLight' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, CapsuleFadeTL_RemoveShadow_018B40864B973FCD649A23BAC2709F23) == 0x001820, "Member 'APlayerPawn_Generic_C::CapsuleFadeTL_RemoveShadow_018B40864B973FCD649A23BAC2709F23' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, CapsuleFadeTL__Direction_018B40864B973FCD649A23BAC2709F23) == 0x001824, "Member 'APlayerPawn_Generic_C::CapsuleFadeTL__Direction_018B40864B973FCD649A23BAC2709F23' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, CapsuleFadeTL) == 0x001828, "Member 'APlayerPawn_Generic_C::CapsuleFadeTL' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Full_Shield_Health_Push_6222ABB047B8F22E3C9FC983BD70CEA6) == 0x001830, "Member 'APlayerPawn_Generic_C::Full_Shield_Health_Push_6222ABB047B8F22E3C9FC983BD70CEA6' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Full_Shield_Health_Impact_6222ABB047B8F22E3C9FC983BD70CEA6) == 0x001834, "Member 'APlayerPawn_Generic_C::Full_Shield_Health_Impact_6222ABB047B8F22E3C9FC983BD70CEA6' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Full_Shield_Health__Direction_6222ABB047B8F22E3C9FC983BD70CEA6) == 0x001838, "Member 'APlayerPawn_Generic_C::Full_Shield_Health__Direction_6222ABB047B8F22E3C9FC983BD70CEA6' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Full_Shield_Health) == 0x001840, "Member 'APlayerPawn_Generic_C::Full_Shield_Health' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Shield_DamageTimeline_Impact_6DC09F024CD096186AE1389FB8061E30) == 0x001848, "Member 'APlayerPawn_Generic_C::Shield_DamageTimeline_Impact_6DC09F024CD096186AE1389FB8061E30' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Shield_DamageTimeline__Direction_6DC09F024CD096186AE1389FB8061E30) == 0x00184C, "Member 'APlayerPawn_Generic_C::Shield_DamageTimeline__Direction_6DC09F024CD096186AE1389FB8061E30' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Shield_DamageTimeline) == 0x001850, "Member 'APlayerPawn_Generic_C::Shield_DamageTimeline' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Shield_Regen_Timeline_Opacity_3DC9958C47D4CEFA60E68699D92BA374) == 0x001858, "Member 'APlayerPawn_Generic_C::Shield_Regen_Timeline_Opacity_3DC9958C47D4CEFA60E68699D92BA374' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Shield_Regen_Timeline_Push_3DC9958C47D4CEFA60E68699D92BA374) == 0x00185C, "Member 'APlayerPawn_Generic_C::Shield_Regen_Timeline_Push_3DC9958C47D4CEFA60E68699D92BA374' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Shield_Regen_Timeline__Direction_3DC9958C47D4CEFA60E68699D92BA374) == 0x001860, "Member 'APlayerPawn_Generic_C::Shield_Regen_Timeline__Direction_3DC9958C47D4CEFA60E68699D92BA374' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Shield_Regen_Timeline) == 0x001868, "Member 'APlayerPawn_Generic_C::Shield_Regen_Timeline' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Shield_ShatterTimeline_Push_F3223F2D4A6B8642F950B0A15F8C6699) == 0x001870, "Member 'APlayerPawn_Generic_C::Shield_ShatterTimeline_Push_F3223F2D4A6B8642F950B0A15F8C6699' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Shield_ShatterTimeline_Opacity_F3223F2D4A6B8642F950B0A15F8C6699) == 0x001874, "Member 'APlayerPawn_Generic_C::Shield_ShatterTimeline_Opacity_F3223F2D4A6B8642F950B0A15F8C6699' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Shield_ShatterTimeline_HighlightCracks_F3223F2D4A6B8642F950B0A15F8C6699) == 0x001878, "Member 'APlayerPawn_Generic_C::Shield_ShatterTimeline_HighlightCracks_F3223F2D4A6B8642F950B0A15F8C6699' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Shield_ShatterTimeline__Direction_F3223F2D4A6B8642F950B0A15F8C6699) == 0x00187C, "Member 'APlayerPawn_Generic_C::Shield_ShatterTimeline__Direction_F3223F2D4A6B8642F950B0A15F8C6699' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Shield_ShatterTimeline) == 0x001880, "Member 'APlayerPawn_Generic_C::Shield_ShatterTimeline' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, HealthSweep_SafetyOpacity_2A96303441845D0EAAAB1EB68183F8A8) == 0x001888, "Member 'APlayerPawn_Generic_C::HealthSweep_SafetyOpacity_2A96303441845D0EAAAB1EB68183F8A8' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, HealthSweep_Sweep_2A96303441845D0EAAAB1EB68183F8A8) == 0x00188C, "Member 'APlayerPawn_Generic_C::HealthSweep_Sweep_2A96303441845D0EAAAB1EB68183F8A8' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, HealthSweep__Direction_2A96303441845D0EAAAB1EB68183F8A8) == 0x001890, "Member 'APlayerPawn_Generic_C::HealthSweep__Direction_2A96303441845D0EAAAB1EB68183F8A8' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, HealthSweep) == 0x001898, "Member 'APlayerPawn_Generic_C::HealthSweep' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, ScreenEffect_PlayerHealthDamageDirection) == 0x0018A0, "Member 'APlayerPawn_Generic_C::ScreenEffect_PlayerHealthDamageDirection' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, ScreenEffect_PlayerHealthDamage) == 0x0018A8, "Member 'APlayerPawn_Generic_C::ScreenEffect_PlayerHealthDamage' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, ScreenEffect_PlayerShieldDamageDirection) == 0x0018B0, "Member 'APlayerPawn_Generic_C::ScreenEffect_PlayerShieldDamageDirection' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, ScreenEffect_PlayerShieldDamage) == 0x0018B8, "Member 'APlayerPawn_Generic_C::ScreenEffect_PlayerShieldDamage' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, HitByHuskProjectileClass) == 0x0018C0, "Member 'APlayerPawn_Generic_C::HitByHuskProjectileClass' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, HitByHuskRangedSound) == 0x0018C8, "Member 'APlayerPawn_Generic_C::HitByHuskRangedSound' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, HitByHuskMeleeSound) == 0x0018D0, "Member 'APlayerPawn_Generic_C::HitByHuskMeleeSound' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, SoulSuckVictimMontage) == 0x0018D8, "Member 'APlayerPawn_Generic_C::SoulSuckVictimMontage' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, PlayerSpeed) == 0x0018E0, "Member 'APlayerPawn_Generic_C::PlayerSpeed' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Run_Particle_Activate_Speed) == 0x0018E4, "Member 'APlayerPawn_Generic_C::Run_Particle_Activate_Speed' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Walk_Dust_Activate_Speed) == 0x0018E8, "Member 'APlayerPawn_Generic_C::Walk_Dust_Activate_Speed' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Walk_Particle_Reset_Speed) == 0x0018EC, "Member 'APlayerPawn_Generic_C::Walk_Particle_Reset_Speed' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, PreviousVelocityVector) == 0x0018F0, "Member 'APlayerPawn_Generic_C::PreviousVelocityVector' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, CanSpawnRunKickupFX_) == 0x0018FC, "Member 'APlayerPawn_Generic_C::CanSpawnRunKickupFX_' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, CanSpawnWalkKickupFX_) == 0x0018FD, "Member 'APlayerPawn_Generic_C::CanSpawnWalkKickupFX_' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, CanSpawnDustLandFX_) == 0x0018FE, "Member 'APlayerPawn_Generic_C::CanSpawnDustLandFX_' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, IsInWater) == 0x0018FF, "Member 'APlayerPawn_Generic_C::IsInWater' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, RunWalkParticleRotation) == 0x001900, "Member 'APlayerPawn_Generic_C::RunWalkParticleRotation' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, IsNinjaInShadowStance_) == 0x00190C, "Member 'APlayerPawn_Generic_C::IsNinjaInShadowStance_' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, GameplayTagsForHitByHuskMeleeSound) == 0x001910, "Member 'APlayerPawn_Generic_C::GameplayTagsForHitByHuskMeleeSound' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Adrenaline_Material) == 0x001930, "Member 'APlayerPawn_Generic_C::Adrenaline_Material' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, AdrenalineRush_HeadAnimatingMIDS) == 0x001938, "Member 'APlayerPawn_Generic_C::AdrenalineRush_HeadAnimatingMIDS' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, AdrenalineRush_BodyAnimatingMIDS) == 0x001948, "Member 'APlayerPawn_Generic_C::AdrenalineRush_BodyAnimatingMIDS' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Adrenaline_Rush_Color_Outer_Direct) == 0x001958, "Member 'APlayerPawn_Generic_C::Adrenaline_Rush_Color_Outer_Direct' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Adrenaline_Rush_Color_Inner_Direct) == 0x001968, "Member 'APlayerPawn_Generic_C::Adrenaline_Rush_Color_Inner_Direct' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Adrenaline_Rush_WPO_Offset) == 0x001978, "Member 'APlayerPawn_Generic_C::Adrenaline_Rush_WPO_Offset' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, P_AdrenalineRushSparklesRunning) == 0x001980, "Member 'APlayerPawn_Generic_C::P_AdrenalineRushSparklesRunning' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Shield_Material) == 0x001988, "Member 'APlayerPawn_Generic_C::Shield_Material' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, BodyShieldMIDArray) == 0x001990, "Member 'APlayerPawn_Generic_C::BodyShieldMIDArray' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, HeadShieldMIDArray) == 0x0019A0, "Member 'APlayerPawn_Generic_C::HeadShieldMIDArray' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Shield_Active) == 0x0019B0, "Member 'APlayerPawn_Generic_C::Shield_Active' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, WaterCounter) == 0x0019B4, "Member 'APlayerPawn_Generic_C::WaterCounter' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Tick_Delta_Seconds) == 0x0019B8, "Member 'APlayerPawn_Generic_C::Tick_Delta_Seconds' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Shield_Damage_Wave_Animation) == 0x0019BC, "Member 'APlayerPawn_Generic_C::Shield_Damage_Wave_Animation' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Overall_Shield_Damage_Wave_Animation_Length) == 0x0019C0, "Member 'APlayerPawn_Generic_C::Overall_Shield_Damage_Wave_Animation_Length' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, size) == 0x0019C4, "Member 'APlayerPawn_Generic_C::size' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Dying) == 0x0019C8, "Member 'APlayerPawn_Generic_C::Dying' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, CanRippleAgain) == 0x0019C9, "Member 'APlayerPawn_Generic_C::CanRippleAgain' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Sound_Shield_Impact) == 0x0019D0, "Member 'APlayerPawn_Generic_C::Sound_Shield_Impact' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Sound_Shield_Destroyed) == 0x0019D8, "Member 'APlayerPawn_Generic_C::Sound_Shield_Destroyed' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Sound_Shield_FullyCharged) == 0x0019E0, "Member 'APlayerPawn_Generic_C::Sound_Shield_FullyCharged' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Sound_Shield_StartRecharge) == 0x0019E8, "Member 'APlayerPawn_Generic_C::Sound_Shield_StartRecharge' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Shield_Shatter_Opacity) == 0x0019F0, "Member 'APlayerPawn_Generic_C::Shield_Shatter_Opacity' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Regen_Opacity) == 0x0019F4, "Member 'APlayerPawn_Generic_C::Regen_Opacity' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Damage_Opacity) == 0x0019F8, "Member 'APlayerPawn_Generic_C::Damage_Opacity' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Default_Shield_opacity) == 0x0019FC, "Member 'APlayerPawn_Generic_C::Default_Shield_opacity' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Shield_PushMinValue) == 0x001A00, "Member 'APlayerPawn_Generic_C::Shield_PushMinValue' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, ShieldVisible_Hit) == 0x001A04, "Member 'APlayerPawn_Generic_C::ShieldVisible_Hit' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, ShieldVisible_Recover) == 0x001A05, "Member 'APlayerPawn_Generic_C::ShieldVisible_Recover' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, ShieldVisible_Shatter) == 0x001A06, "Member 'APlayerPawn_Generic_C::ShieldVisible_Shatter' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, ShieldVisible_FullHealth) == 0x001A07, "Member 'APlayerPawn_Generic_C::ShieldVisible_FullHealth' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Fully_Regened_Shield_health_Opacity) == 0x001A08, "Member 'APlayerPawn_Generic_C::Fully_Regened_Shield_health_Opacity' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, TC_GameplayCueDamageShielded) == 0x001A10, "Member 'APlayerPawn_Generic_C::TC_GameplayCueDamageShielded' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, LatestDamageIsShieldDamage) == 0x001A30, "Member 'APlayerPawn_Generic_C::LatestDamageIsShieldDamage' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Damage_Taken) == 0x001A34, "Member 'APlayerPawn_Generic_C::Damage_Taken' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Last_Shield_Damage_Time) == 0x001A38, "Member 'APlayerPawn_Generic_C::Last_Shield_Damage_Time' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, CharmShieldMIDArray) == 0x001A40, "Member 'APlayerPawn_Generic_C::CharmShieldMIDArray' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, BodyValid) == 0x001A50, "Member 'APlayerPawn_Generic_C::BodyValid' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, BackpackValid) == 0x001A51, "Member 'APlayerPawn_Generic_C::BackpackValid' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, HatValid) == 0x001A52, "Member 'APlayerPawn_Generic_C::HatValid' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, FaceValid) == 0x001A53, "Member 'APlayerPawn_Generic_C::FaceValid' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, CharmValid) == 0x001A54, "Member 'APlayerPawn_Generic_C::CharmValid' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, HeadValid) == 0x001A55, "Member 'APlayerPawn_Generic_C::HeadValid' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, AdrenalineRush_CharmAnimatingMIDS) == 0x001A58, "Member 'APlayerPawn_Generic_C::AdrenalineRush_CharmAnimatingMIDS' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Adrenaline_Rush_MID_Collection) == 0x001A68, "Member 'APlayerPawn_Generic_C::Adrenaline_Rush_MID_Collection' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, P_DBNOResurrect) == 0x001A78, "Member 'APlayerPawn_Generic_C::P_DBNOResurrect' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, DBNOResurrectSound) == 0x001A80, "Member 'APlayerPawn_Generic_C::DBNOResurrectSound' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, On_Player_Built_Floor) == 0x001A88, "Member 'APlayerPawn_Generic_C::On_Player_Built_Floor' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Event_NeedRoadsActive) == 0x001A90, "Member 'APlayerPawn_Generic_C::Event_NeedRoadsActive' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Event_NeedRoadsDeactive) == 0x001A98, "Member 'APlayerPawn_Generic_C::Event_NeedRoadsDeactive' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, TC_WhereWereGoingWeNeedRoads) == 0x001AA0, "Member 'APlayerPawn_Generic_C::TC_WhereWereGoingWeNeedRoads' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Effect_Player_LandedDust) == 0x001AC0, "Member 'APlayerPawn_Generic_C::Effect_Player_LandedDust' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, P_GravitySphere_LeftFoot) == 0x001AC8, "Member 'APlayerPawn_Generic_C::P_GravitySphere_LeftFoot' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, TempArray) == 0x001AD0, "Member 'APlayerPawn_Generic_C::TempArray' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, P_GravitySphere_RightFoot) == 0x001AE0, "Member 'APlayerPawn_Generic_C::P_GravitySphere_RightFoot' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Effect_Player_GravitySphereFeet) == 0x001AE8, "Member 'APlayerPawn_Generic_C::Effect_Player_GravitySphereFeet' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Shield_BodySkeletalMesh) == 0x001AF0, "Member 'APlayerPawn_Generic_C::Shield_BodySkeletalMesh' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Shield_HeadSkeletalMesh) == 0x001AF8, "Member 'APlayerPawn_Generic_C::Shield_HeadSkeletalMesh' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Shield_CharmSkeletalMesh) == 0x001B00, "Member 'APlayerPawn_Generic_C::Shield_CharmSkeletalMesh' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Adrenaline_Rush_Body) == 0x001B08, "Member 'APlayerPawn_Generic_C::Adrenaline_Rush_Body' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Adrenaline_Rush_Head) == 0x001B10, "Member 'APlayerPawn_Generic_C::Adrenaline_Rush_Head' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Adrenaline_Rush_Charm) == 0x001B18, "Member 'APlayerPawn_Generic_C::Adrenaline_Rush_Charm' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Sound_Player_Hit) == 0x001B20, "Member 'APlayerPawn_Generic_C::Sound_Player_Hit' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, DamageForceFeedback) == 0x001B28, "Member 'APlayerPawn_Generic_C::DamageForceFeedback' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, DBNOParticles) == 0x001B30, "Member 'APlayerPawn_Generic_C::DBNOParticles' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Effect_Player_Landed_WindVector_P) == 0x001B38, "Member 'APlayerPawn_Generic_C::Effect_Player_Landed_WindVector_P' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, SpeechBubbleWidgetClass) == 0x001B40, "Member 'APlayerPawn_Generic_C::SpeechBubbleWidgetClass' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, LastSpeechText) == 0x001B48, "Member 'APlayerPawn_Generic_C::LastSpeechText' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, DamageCameraShake) == 0x001B60, "Member 'APlayerPawn_Generic_C::DamageCameraShake' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, UseAnimTrailsNotifies) == 0x001B68, "Member 'APlayerPawn_Generic_C::UseAnimTrailsNotifies' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Time_when_you_ll_be_able_to_splash_again) == 0x001B6C, "Member 'APlayerPawn_Generic_C::Time_when_you_ll_be_able_to_splash_again' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, CurrentWaterMeshActor) == 0x001B70, "Member 'APlayerPawn_Generic_C::CurrentWaterMeshActor' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, WaterTraceHitLocation) == 0x001B78, "Member 'APlayerPawn_Generic_C::WaterTraceHitLocation' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, StableVelocityVector) == 0x001C00, "Member 'APlayerPawn_Generic_C::StableVelocityVector' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, PlayerRunTemplate_Ground) == 0x001C10, "Member 'APlayerPawn_Generic_C::PlayerRunTemplate_Ground' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, PlayerWalkTemplate_Ground) == 0x001C18, "Member 'APlayerPawn_Generic_C::PlayerWalkTemplate_Ground' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, PlayerRunTemplate_Water) == 0x001C20, "Member 'APlayerPawn_Generic_C::PlayerRunTemplate_Water' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, PlayerWalkTemplate_Water) == 0x001C28, "Member 'APlayerPawn_Generic_C::PlayerWalkTemplate_Water' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Pawn_Charm_Skeletal_Mesh) == 0x001C30, "Member 'APlayerPawn_Generic_C::Pawn_Charm_Skeletal_Mesh' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, DefaultShieldOpacity) == 0x001C38, "Member 'APlayerPawn_Generic_C::DefaultShieldOpacity' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, AnimTrailsPS_Ref) == 0x001C40, "Member 'APlayerPawn_Generic_C::AnimTrailsPS_Ref' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Adrenaline_Rush_Color_Outer_Periodic) == 0x001C48, "Member 'APlayerPawn_Generic_C::Adrenaline_Rush_Color_Outer_Periodic' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, WeaponMaterialOverride) == 0x001C58, "Member 'APlayerPawn_Generic_C::WeaponMaterialOverride' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Adrenaline_Rush_Color_Inner_Periodic) == 0x001C60, "Member 'APlayerPawn_Generic_C::Adrenaline_Rush_Color_Inner_Periodic' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, TickWaterLevel) == 0x001C70, "Member 'APlayerPawn_Generic_C::TickWaterLevel' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, WetnessDepthTexture) == 0x001C78, "Member 'APlayerPawn_Generic_C::WetnessDepthTexture' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, WaterLevelMID) == 0x001C80, "Member 'APlayerPawn_Generic_C::WaterLevelMID' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, WaterDecayMID) == 0x001C88, "Member 'APlayerPawn_Generic_C::WaterDecayMID' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Was_RTT_Enabled_Var_Set) == 0x001C90, "Member 'APlayerPawn_Generic_C::Was_RTT_Enabled_Var_Set' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Water_Scene_Capture_Enabled) == 0x001C91, "Member 'APlayerPawn_Generic_C::Water_Scene_Capture_Enabled' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, StartingMinCapsuleShadowVis) == 0x001C94, "Member 'APlayerPawn_Generic_C::StartingMinCapsuleShadowVis' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, CachedEffect) == 0x001C98, "Member 'APlayerPawn_Generic_C::CachedEffect' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, WaterInteractionWakeMIDS) == 0x001CA0, "Member 'APlayerPawn_Generic_C::WaterInteractionWakeMIDS' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, WaterInteractionWakeMeshes) == 0x001CB0, "Member 'APlayerPawn_Generic_C::WaterInteractionWakeMeshes' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, Character_Calve_Length) == 0x001CC0, "Member 'APlayerPawn_Generic_C::Character_Calve_Length' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, NumberOfCyclingWaterMeshes) == 0x001CC4, "Member 'APlayerPawn_Generic_C::NumberOfCyclingWaterMeshes' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, WaterTraceImpactNormalAndZHeightLocation) == 0x001CC8, "Member 'APlayerPawn_Generic_C::WaterTraceImpactNormalAndZHeightLocation' has a wrong offset!");
static_assert(offsetof(APlayerPawn_Generic_C, PlayerVelocity) == 0x001CD8, "Member 'APlayerPawn_Generic_C::PlayerVelocity' has a wrong offset!");

}

