#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TencentTSS

#include "Basic.hpp"

#include "PacketHandler_classes.hpp"


namespace SDK
{

// Class TencentTSS.TencentHandlerComponentFactory
// 0x0000 (0x0028 - 0x0028)
class UTencentHandlerComponentFactory final : public UHandlerComponentFactory
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"TencentHandlerComponentFactory">();
	}
	static class UTencentHandlerComponentFactory* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTencentHandlerComponentFactory>();
	}
};
static_assert(alignof(UTencentHandlerComponentFactory) == 0x000008, "Wrong alignment on UTencentHandlerComponentFactory");
static_assert(sizeof(UTencentHandlerComponentFactory) == 0x000028, "Wrong size on UTencentHandlerComponentFactory");

}

