#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyle_LargeButton_Disabled

#include "Basic.hpp"

#include "TextStyle_MediumButton_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-LargeButton-Disabled.TextStyle-LargeButton-Disabled_C
// 0x0000 (0x00C0 - 0x00C0)
class UTextStyle_LargeButton_Disabled_C final : public UTextStyle_MediumButton_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-LargeButton-Disabled_C">();
	}
	static class UTextStyle_LargeButton_Disabled_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyle_LargeButton_Disabled_C>();
	}
};
static_assert(alignof(UTextStyle_LargeButton_Disabled_C) == 0x000008, "Wrong alignment on UTextStyle_LargeButton_Disabled_C");
static_assert(sizeof(UTextStyle_LargeButton_Disabled_C) == 0x0000C0, "Wrong size on UTextStyle_LargeButton_Disabled_C");

}

