#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TODM_A

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function TODM_A.TODM_A_C.ExecuteUbergraph_TODM_A
// 0x01B0 (0x01B0 - 0x0000)
struct TODM_A_C_ExecuteUbergraph_TODM_A final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_FFloor_ReturnValue;                       // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Conv_IntToBool_ReturnValue;               // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0010(0x0010)(ZeroConstructor, NoDestructor)
	float                                         CallFunc_Square_ReturnValue;                       // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue1;         // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameUserSettings*                      CallFunc_GetGameUserSettings_ReturnValue;          // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetShadowQuality_ReturnValue;             // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3D[0x3];                                       // 0x003D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Conv_BoolToFloat_ReturnValue;             // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0045(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0046(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0047(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_RandomFloatInRange_ReturnValue;           // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0050(0x0008)(NoDestructor)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue12;        // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetStormStrength_ReturnValue;             // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue123;       // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Enable;                         // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue1;                 // 0x0069(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6A[0x2];                                       // 0x006A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           CallFunc_GetLightColor_ReturnValue;                // 0x006C(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakColor_R;                             // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakColor_G;                             // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakColor_B;                             // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakColor_A;                             // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_LinearColorLerp_ReturnValue;              // 0x008C(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue1234;      // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakColor_R1;                            // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakColor_G1;                            // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakColor_B1;                            // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakColor_A1;                            // 0x00AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue12345;     // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue123456;    // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue1234567;   // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue12345678;  // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue1;              // 0x00C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue123456789; // 0x00C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue12;             // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue123;            // 0x00CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue1234;           // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue12345678910; // 0x00D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue12345;          // 0x00DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x00E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_RandomFloatInRange_ReturnValue1;          // 0x00E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue1;           // 0x00E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_MakeColor_ReturnValue;                    // 0x00EC(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FClamp_ReturnValue;                       // 0x00FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue123456;         // 0x0100(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FClamp_ReturnValue1;                      // 0x0104(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue1234567;        // 0x0108(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_MakeColor_ReturnValue1;                   // 0x010C(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_MakeColor_ReturnValue12;                  // 0x011C(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FClamp_ReturnValue12;                     // 0x012C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FClamp_ReturnValue123;                    // 0x0130(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue12345678;       // 0x0134(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue123456789;      // 0x0138(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_MakeColor_ReturnValue123;                 // 0x013C(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_MakeColor_ReturnValue1234;                // 0x014C(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FClamp_ReturnValue1234;                   // 0x015C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue12345678910;    // 0x0160(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FClamp_ReturnValue12345;                  // 0x0164(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue1234567891011;  // 0x0168(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_MakeColor_ReturnValue12345;               // 0x016C(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_MakeColor_ReturnValue123456;              // 0x017C(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FClamp_ReturnValue123456;                 // 0x018C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue123456789101112; // 0x0190(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FClamp_ReturnValue1234567;                // 0x0194(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue12345678910111213; // 0x0198(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_MakeColor_ReturnValue1234567;             // 0x019C(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(TODM_A_C_ExecuteUbergraph_TODM_A) == 0x000008, "Wrong alignment on TODM_A_C_ExecuteUbergraph_TODM_A");
static_assert(sizeof(TODM_A_C_ExecuteUbergraph_TODM_A) == 0x0001B0, "Wrong size on TODM_A_C_ExecuteUbergraph_TODM_A");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, EntryPoint) == 0x000000, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::EntryPoint' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_FFloor_ReturnValue) == 0x000004, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_FFloor_ReturnValue' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Conv_IntToBool_ReturnValue) == 0x000008, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Conv_IntToBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Square_ReturnValue) == 0x000020, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Square_ReturnValue' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x000024, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Multiply_FloatFloat_ReturnValue1) == 0x000028, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Multiply_FloatFloat_ReturnValue1' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_GetGameUserSettings_ReturnValue) == 0x000030, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_GetGameUserSettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_GetShadowQuality_ReturnValue) == 0x000038, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_GetShadowQuality_ReturnValue' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Greater_IntInt_ReturnValue) == 0x00003C, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Conv_BoolToFloat_ReturnValue) == 0x000040, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Conv_BoolToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, K2Node_SwitchInteger_CmpSuccess) == 0x000044, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, Temp_bool_Variable) == 0x000045, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Not_PreBool_ReturnValue) == 0x000046, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_BooleanOR_ReturnValue) == 0x000047, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_RandomFloatInRange_ReturnValue) == 0x000048, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000050, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Multiply_FloatFloat_ReturnValue12) == 0x000058, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Multiply_FloatFloat_ReturnValue12' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_GetStormStrength_ReturnValue) == 0x00005C, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_GetStormStrength_ReturnValue' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Multiply_FloatFloat_ReturnValue123) == 0x000060, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Multiply_FloatFloat_ReturnValue123' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Add_FloatFloat_ReturnValue) == 0x000064, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, K2Node_CustomEvent_Enable) == 0x000068, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::K2Node_CustomEvent_Enable' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Not_PreBool_ReturnValue1) == 0x000069, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Not_PreBool_ReturnValue1' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_GetLightColor_ReturnValue) == 0x00006C, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_GetLightColor_ReturnValue' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_BreakColor_R) == 0x00007C, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_BreakColor_R' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_BreakColor_G) == 0x000080, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_BreakColor_G' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_BreakColor_B) == 0x000084, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_BreakColor_B' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_BreakColor_A) == 0x000088, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_BreakColor_A' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_LinearColorLerp_ReturnValue) == 0x00008C, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_LinearColorLerp_ReturnValue' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Multiply_FloatFloat_ReturnValue1234) == 0x00009C, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Multiply_FloatFloat_ReturnValue1234' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_BreakColor_R1) == 0x0000A0, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_BreakColor_R1' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_BreakColor_G1) == 0x0000A4, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_BreakColor_G1' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_BreakColor_B1) == 0x0000A8, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_BreakColor_B1' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_BreakColor_A1) == 0x0000AC, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_BreakColor_A1' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Multiply_FloatFloat_ReturnValue12345) == 0x0000B0, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Multiply_FloatFloat_ReturnValue12345' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Multiply_FloatFloat_ReturnValue123456) == 0x0000B4, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Multiply_FloatFloat_ReturnValue123456' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Multiply_FloatFloat_ReturnValue1234567) == 0x0000B8, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Multiply_FloatFloat_ReturnValue1234567' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Multiply_FloatFloat_ReturnValue12345678) == 0x0000BC, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Multiply_FloatFloat_ReturnValue12345678' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Add_FloatFloat_ReturnValue1) == 0x0000C0, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Add_FloatFloat_ReturnValue1' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Multiply_FloatFloat_ReturnValue123456789) == 0x0000C4, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Multiply_FloatFloat_ReturnValue123456789' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Add_FloatFloat_ReturnValue12) == 0x0000C8, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Add_FloatFloat_ReturnValue12' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Add_FloatFloat_ReturnValue123) == 0x0000CC, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Add_FloatFloat_ReturnValue123' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Add_FloatFloat_ReturnValue1234) == 0x0000D0, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Add_FloatFloat_ReturnValue1234' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Multiply_FloatFloat_ReturnValue12345678910) == 0x0000D4, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Multiply_FloatFloat_ReturnValue12345678910' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x0000D8, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Add_FloatFloat_ReturnValue12345) == 0x0000DC, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Add_FloatFloat_ReturnValue12345' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Divide_FloatFloat_ReturnValue) == 0x0000E0, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_RandomFloatInRange_ReturnValue1) == 0x0000E4, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_RandomFloatInRange_ReturnValue1' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Divide_FloatFloat_ReturnValue1) == 0x0000E8, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Divide_FloatFloat_ReturnValue1' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_MakeColor_ReturnValue) == 0x0000EC, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_MakeColor_ReturnValue' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_FClamp_ReturnValue) == 0x0000FC, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_FClamp_ReturnValue' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Add_FloatFloat_ReturnValue123456) == 0x000100, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Add_FloatFloat_ReturnValue123456' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_FClamp_ReturnValue1) == 0x000104, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_FClamp_ReturnValue1' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Add_FloatFloat_ReturnValue1234567) == 0x000108, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Add_FloatFloat_ReturnValue1234567' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_MakeColor_ReturnValue1) == 0x00010C, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_MakeColor_ReturnValue1' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_MakeColor_ReturnValue12) == 0x00011C, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_MakeColor_ReturnValue12' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_FClamp_ReturnValue12) == 0x00012C, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_FClamp_ReturnValue12' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_FClamp_ReturnValue123) == 0x000130, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_FClamp_ReturnValue123' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Add_FloatFloat_ReturnValue12345678) == 0x000134, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Add_FloatFloat_ReturnValue12345678' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Add_FloatFloat_ReturnValue123456789) == 0x000138, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Add_FloatFloat_ReturnValue123456789' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_MakeColor_ReturnValue123) == 0x00013C, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_MakeColor_ReturnValue123' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_MakeColor_ReturnValue1234) == 0x00014C, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_MakeColor_ReturnValue1234' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_FClamp_ReturnValue1234) == 0x00015C, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_FClamp_ReturnValue1234' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Add_FloatFloat_ReturnValue12345678910) == 0x000160, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Add_FloatFloat_ReturnValue12345678910' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_FClamp_ReturnValue12345) == 0x000164, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_FClamp_ReturnValue12345' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Add_FloatFloat_ReturnValue1234567891011) == 0x000168, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Add_FloatFloat_ReturnValue1234567891011' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_MakeColor_ReturnValue12345) == 0x00016C, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_MakeColor_ReturnValue12345' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_MakeColor_ReturnValue123456) == 0x00017C, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_MakeColor_ReturnValue123456' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_FClamp_ReturnValue123456) == 0x00018C, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_FClamp_ReturnValue123456' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Add_FloatFloat_ReturnValue123456789101112) == 0x000190, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Add_FloatFloat_ReturnValue123456789101112' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_FClamp_ReturnValue1234567) == 0x000194, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_FClamp_ReturnValue1234567' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_Add_FloatFloat_ReturnValue12345678910111213) == 0x000198, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_Add_FloatFloat_ReturnValue12345678910111213' has a wrong offset!");
static_assert(offsetof(TODM_A_C_ExecuteUbergraph_TODM_A, CallFunc_MakeColor_ReturnValue1234567) == 0x00019C, "Member 'TODM_A_C_ExecuteUbergraph_TODM_A::CallFunc_MakeColor_ReturnValue1234567' has a wrong offset!");

// Function TODM_A.TODM_A_C.DisableLightAndFog
// 0x0001 (0x0001 - 0x0000)
struct TODM_A_C_DisableLightAndFog final
{
public:
	bool                                          Enable;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(TODM_A_C_DisableLightAndFog) == 0x000001, "Wrong alignment on TODM_A_C_DisableLightAndFog");
static_assert(sizeof(TODM_A_C_DisableLightAndFog) == 0x000001, "Wrong size on TODM_A_C_DisableLightAndFog");
static_assert(offsetof(TODM_A_C_DisableLightAndFog, Enable) == 0x000000, "Member 'TODM_A_C_DisableLightAndFog::Enable' has a wrong offset!");

// Function TODM_A.TODM_A_C.UserConstructionScript
// 0x00C0 (0x00C0 - 0x0000)
struct TODM_A_C_UserConstructionScript final
{
public:
	float                                         CallFunc_FClamp_ReturnValue;                       // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FClamp_ReturnValue1;                      // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue1;              // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_MakeColor_ReturnValue;                    // 0x0010(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_MakeColor_ReturnValue1;                   // 0x0020(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FClamp_ReturnValue12;                     // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue12;             // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FClamp_ReturnValue123;                    // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue123;            // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_MakeColor_ReturnValue12;                  // 0x0040(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_MakeColor_ReturnValue123;                 // 0x0050(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FClamp_ReturnValue1234;                   // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue1234;           // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FClamp_ReturnValue12345;                  // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue12345;          // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_MakeColor_ReturnValue1234;                // 0x0070(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_MakeColor_ReturnValue12345;               // 0x0080(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FClamp_ReturnValue123456;                 // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue123456;         // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FClamp_ReturnValue1234567;                // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue1234567;        // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_MakeColor_ReturnValue123456;              // 0x00A0(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_MakeColor_ReturnValue1234567;             // 0x00B0(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(TODM_A_C_UserConstructionScript) == 0x000004, "Wrong alignment on TODM_A_C_UserConstructionScript");
static_assert(sizeof(TODM_A_C_UserConstructionScript) == 0x0000C0, "Wrong size on TODM_A_C_UserConstructionScript");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_FClamp_ReturnValue) == 0x000000, "Member 'TODM_A_C_UserConstructionScript::CallFunc_FClamp_ReturnValue' has a wrong offset!");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_FClamp_ReturnValue1) == 0x000004, "Member 'TODM_A_C_UserConstructionScript::CallFunc_FClamp_ReturnValue1' has a wrong offset!");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_Add_FloatFloat_ReturnValue) == 0x000008, "Member 'TODM_A_C_UserConstructionScript::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_Add_FloatFloat_ReturnValue1) == 0x00000C, "Member 'TODM_A_C_UserConstructionScript::CallFunc_Add_FloatFloat_ReturnValue1' has a wrong offset!");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_MakeColor_ReturnValue) == 0x000010, "Member 'TODM_A_C_UserConstructionScript::CallFunc_MakeColor_ReturnValue' has a wrong offset!");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_MakeColor_ReturnValue1) == 0x000020, "Member 'TODM_A_C_UserConstructionScript::CallFunc_MakeColor_ReturnValue1' has a wrong offset!");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_FClamp_ReturnValue12) == 0x000030, "Member 'TODM_A_C_UserConstructionScript::CallFunc_FClamp_ReturnValue12' has a wrong offset!");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_Add_FloatFloat_ReturnValue12) == 0x000034, "Member 'TODM_A_C_UserConstructionScript::CallFunc_Add_FloatFloat_ReturnValue12' has a wrong offset!");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_FClamp_ReturnValue123) == 0x000038, "Member 'TODM_A_C_UserConstructionScript::CallFunc_FClamp_ReturnValue123' has a wrong offset!");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_Add_FloatFloat_ReturnValue123) == 0x00003C, "Member 'TODM_A_C_UserConstructionScript::CallFunc_Add_FloatFloat_ReturnValue123' has a wrong offset!");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_MakeColor_ReturnValue12) == 0x000040, "Member 'TODM_A_C_UserConstructionScript::CallFunc_MakeColor_ReturnValue12' has a wrong offset!");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_MakeColor_ReturnValue123) == 0x000050, "Member 'TODM_A_C_UserConstructionScript::CallFunc_MakeColor_ReturnValue123' has a wrong offset!");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_FClamp_ReturnValue1234) == 0x000060, "Member 'TODM_A_C_UserConstructionScript::CallFunc_FClamp_ReturnValue1234' has a wrong offset!");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_Add_FloatFloat_ReturnValue1234) == 0x000064, "Member 'TODM_A_C_UserConstructionScript::CallFunc_Add_FloatFloat_ReturnValue1234' has a wrong offset!");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_FClamp_ReturnValue12345) == 0x000068, "Member 'TODM_A_C_UserConstructionScript::CallFunc_FClamp_ReturnValue12345' has a wrong offset!");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_Add_FloatFloat_ReturnValue12345) == 0x00006C, "Member 'TODM_A_C_UserConstructionScript::CallFunc_Add_FloatFloat_ReturnValue12345' has a wrong offset!");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_MakeColor_ReturnValue1234) == 0x000070, "Member 'TODM_A_C_UserConstructionScript::CallFunc_MakeColor_ReturnValue1234' has a wrong offset!");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_MakeColor_ReturnValue12345) == 0x000080, "Member 'TODM_A_C_UserConstructionScript::CallFunc_MakeColor_ReturnValue12345' has a wrong offset!");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_FClamp_ReturnValue123456) == 0x000090, "Member 'TODM_A_C_UserConstructionScript::CallFunc_FClamp_ReturnValue123456' has a wrong offset!");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_Add_FloatFloat_ReturnValue123456) == 0x000094, "Member 'TODM_A_C_UserConstructionScript::CallFunc_Add_FloatFloat_ReturnValue123456' has a wrong offset!");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_FClamp_ReturnValue1234567) == 0x000098, "Member 'TODM_A_C_UserConstructionScript::CallFunc_FClamp_ReturnValue1234567' has a wrong offset!");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_Add_FloatFloat_ReturnValue1234567) == 0x00009C, "Member 'TODM_A_C_UserConstructionScript::CallFunc_Add_FloatFloat_ReturnValue1234567' has a wrong offset!");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_MakeColor_ReturnValue123456) == 0x0000A0, "Member 'TODM_A_C_UserConstructionScript::CallFunc_MakeColor_ReturnValue123456' has a wrong offset!");
static_assert(offsetof(TODM_A_C_UserConstructionScript, CallFunc_MakeColor_ReturnValue1234567) == 0x0000B0, "Member 'TODM_A_C_UserConstructionScript::CallFunc_MakeColor_ReturnValue1234567' has a wrong offset!");

}

